// src/redux/clients/clientsConstants.js

// Fetch clients
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';
export const FETCH_CLIENTS_RESET = 'FETCH_CLIENTS_RESET';

// Add client
export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';
export const ADD_CLIENT_RESET = 'ADD_CLIENT_RESET';

// Update client
export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE';
export const UPDATE_CLIENT_RESET = 'UPDATE_CLIENT_RESET';

// Delete client
export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE';
export const DELETE_CLIENT_RESET = 'DELETE_CLIENT_RESET';

// UI actions
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_EDITING_CLIENT = 'SET_EDITING_CLIENT';
export const CLEAR_ERROR = 'CLEAR_ERROR';