export const FETCH_PLANNED_COLLECTIONS_REQUEST = 'FETCH_PLANNED_COLLECTIONS_REQUEST';
export const FETCH_PLANNED_COLLECTIONS_SUCCESS = 'FETCH_PLANNED_COLLECTIONS_SUCCESS';
export const FETCH_PLANNED_COLLECTIONS_FAIL = 'FETCH_PLANNED_COLLECTIONS_FAIL';

export const FETCH_PROCESSES_REQUEST = 'FETCH_PROCESSES_REQUEST';
export const FETCH_PROCESSES_SUCCESS = 'FETCH_PROCESSES_SUCCESS';
export const FETCH_PROCESSES_FAIL = 'FETCH_PROCESSES_FAIL';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const ADD_PLANNED_COLLECTION_REQUEST = 'ADD_PLANNED_COLLECTION_REQUEST';
export const ADD_PLANNED_COLLECTION_SUCCESS = 'ADD_PLANNED_COLLECTION_SUCCESS';
export const ADD_PLANNED_COLLECTION_FAIL = 'ADD_PLANNED_COLLECTION_FAIL';

export const UPDATE_PLANNED_COLLECTION_REQUEST = 'UPDATE_PLANNED_COLLECTION_REQUEST';
export const UPDATE_PLANNED_COLLECTION_SUCCESS = 'UPDATE_PLANNED_COLLECTION_SUCCESS';
export const UPDATE_PLANNED_COLLECTION_FAIL = 'UPDATE_PLANNED_COLLECTION_FAIL';

export const DELETE_PLANNED_COLLECTION_REQUEST = 'DELETE_PLANNED_COLLECTION_REQUEST';
export const DELETE_PLANNED_COLLECTION_SUCCESS = 'DELETE_PLANNED_COLLECTION_SUCCESS';
export const DELETE_PLANNED_COLLECTION_FAIL = 'DELETE_PLANNED_COLLECTION_FAIL';

export const SET_SELECTED_MONTH = 'SET_SELECTED_MONTH';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_NEW_ENTRY = 'SET_NEW_ENTRY';
export const RESET_NEW_ENTRY = 'RESET_NEW_ENTRY';

// Add these to the existing constants file
export const FETCH_RECEIVED_DATA_REQUEST = 'FETCH_RECEIVED_DATA_REQUEST';
export const FETCH_RECEIVED_DATA_SUCCESS = 'FETCH_RECEIVED_DATA_SUCCESS';
export const FETCH_RECEIVED_DATA_FAIL = 'FETCH_RECEIVED_DATA_FAIL';

export const ADD_RECEIVED_ENTRY_REQUEST = 'ADD_RECEIVED_ENTRY_REQUEST';
export const ADD_RECEIVED_ENTRY_SUCCESS = 'ADD_RECEIVED_ENTRY_SUCCESS';
export const ADD_RECEIVED_ENTRY_FAIL = 'ADD_RECEIVED_ENTRY_FAIL';

export const UPDATE_RECEIVED_ENTRY_REQUEST = 'UPDATE_RECEIVED_ENTRY_REQUEST';
export const UPDATE_RECEIVED_ENTRY_SUCCESS = 'UPDATE_RECEIVED_ENTRY_SUCCESS';
export const UPDATE_RECEIVED_ENTRY_FAIL = 'UPDATE_RECEIVED_ENTRY_FAIL';

export const DELETE_RECEIVED_ENTRY_REQUEST = 'DELETE_RECEIVED_ENTRY_REQUEST';
export const DELETE_RECEIVED_ENTRY_SUCCESS = 'DELETE_RECEIVED_ENTRY_SUCCESS';
export const DELETE_RECEIVED_ENTRY_FAIL = 'DELETE_RECEIVED_ENTRY_FAIL';

export const SET_RECEIVED_FORM_DATA = 'SET_RECEIVED_FORM_DATA';
export const RESET_RECEIVED_FORM_DATA = 'RESET_RECEIVED_FORM_DATA';
export const SET_RECEIVED_PAGINATION = 'SET_RECEIVED_PAGINATION';


// Distribution constants
export const FETCH_DISTRIBUTIONS_REQUEST = 'FETCH_DISTRIBUTIONS_REQUEST';
export const FETCH_DISTRIBUTIONS_SUCCESS = 'FETCH_DISTRIBUTIONS_SUCCESS';
export const FETCH_DISTRIBUTIONS_FAIL = 'FETCH_DISTRIBUTIONS_FAIL';

export const ADD_DISTRIBUTION_REQUEST = 'ADD_DISTRIBUTION_REQUEST';
export const ADD_DISTRIBUTION_SUCCESS = 'ADD_DISTRIBUTION_SUCCESS';
export const ADD_DISTRIBUTION_FAIL = 'ADD_DISTRIBUTION_FAIL';

export const UPDATE_DISTRIBUTION_REQUEST = 'UPDATE_DISTRIBUTION_REQUEST';
export const UPDATE_DISTRIBUTION_SUCCESS = 'UPDATE_DISTRIBUTION_SUCCESS';
export const UPDATE_DISTRIBUTION_FAIL = 'UPDATE_DISTRIBUTION_FAIL';

export const DELETE_DISTRIBUTION_REQUEST = 'DELETE_DISTRIBUTION_REQUEST';
export const DELETE_DISTRIBUTION_SUCCESS = 'DELETE_DISTRIBUTION_SUCCESS';
export const DELETE_DISTRIBUTION_FAIL = 'DELETE_DISTRIBUTION_FAIL';

export const SET_DISTRIBUTION_FORM_DATA = 'SET_DISTRIBUTION_FORM_DATA';
export const RESET_DISTRIBUTION_FORM_DATA = 'RESET_DISTRIBUTION_FORM_DATA';

export const SET_DISTRIBUTION_PAGINATION = 'SET_DISTRIBUTION_PAGINATION';

export const SET_DISTRIBUTION_SELECTED_MONTH = 'SET_DISTRIBUTION_SELECTED_MONTH';
export const SET_DISTRIBUTION_SEARCH_TERM = 'SET_DISTRIBUTION_SEARCH_TERM';
