export const GET_ATTENDANCE_COUNT_REQUEST = 'GET_ATTENDANCE_COUNT_REQUEST'
export const GET_ATTENDANCE_COUNT_SUCCESS = 'GET_ATTENDANCE_COUNT_SUCCESS'
export const GET_ATTENDANCE_COUNT_FAIL = 'GET_ATTENDANCE_COUNT_FAIL'
export const ATTENDANCE_COUNT_RESET = 'ATTENDANCE_COUNT_RESET' 