// src/redux/constants/employeeReportsConstants.js

// Attendance Constants
export const FETCH_ATTENDANCE_REQUEST = "FETCH_ATTENDANCE_REQUEST";
export const FETCH_ATTENDANCE_SUCCESS = "FETCH_ATTENDANCE_SUCCESS";
export const FETCH_ATTENDANCE_FAIL = "FETCH_ATTENDANCE_FAIL";

// Verification Constants (for reports)
export const FETCH_REPORT_VERIFICATIONS_REQUEST = "FETCH_REPORT_VERIFICATIONS_REQUEST";
export const FETCH_REPORT_VERIFICATIONS_SUCCESS = "FETCH_REPORT_VERIFICATIONS_SUCCESS";
export const FETCH_REPORT_VERIFICATIONS_FAIL = "FETCH_REPORT_VERIFICATIONS_FAIL";

// Planned Collections Constants
export const FETCH_PLANNED_COLLECTIONS_REQUEST = "FETCH_PLANNED_COLLECTIONS_REQUEST";
export const FETCH_PLANNED_COLLECTIONS_SUCCESS = "FETCH_PLANNED_COLLECTIONS_SUCCESS";
export const FETCH_PLANNED_COLLECTIONS_FAIL = "FETCH_PLANNED_COLLECTIONS_FAIL";

// Received Collections Constants
export const FETCH_RECEIVED_COLLECTIONS_REQUEST = "FETCH_RECEIVED_COLLECTIONS_REQUEST";
export const FETCH_RECEIVED_COLLECTIONS_SUCCESS = "FETCH_RECEIVED_COLLECTIONS_SUCCESS";
export const FETCH_RECEIVED_COLLECTIONS_FAIL = "FETCH_RECEIVED_COLLECTIONS_FAIL";

// Distributions Constants
export const FETCH_DISTRIBUTIONS_REQUEST = "FETCH_DISTRIBUTIONS_REQUEST";
export const FETCH_DISTRIBUTIONS_SUCCESS = "FETCH_DISTRIBUTIONS_SUCCESS";
export const FETCH_DISTRIBUTIONS_FAIL = "FETCH_DISTRIBUTIONS_FAIL";

// Combined Report Data Fetch
export const FETCH_REPORT_DATA_REQUEST = "FETCH_REPORT_DATA_REQUEST";
export const FETCH_REPORT_DATA_SUCCESS = "FETCH_REPORT_DATA_SUCCESS";
export const FETCH_REPORT_DATA_FAIL = "FETCH_REPORT_DATA_FAIL";

// Update Selected Month
export const UPDATE_SELECTED_MONTH = "UPDATE_SELECTED_MONTH";

// Update Pagination
export const UPDATE_ATTENDANCE_PAGINATION = "UPDATE_ATTENDANCE_PAGINATION";
export const UPDATE_VERIFICATION_PAGINATION = "UPDATE_VERIFICATION_PAGINATION";

// Clear Errors
export const CLEAR_REPORT_ERRORS = "CLEAR_REPORT_ERRORS";