export const FIXED_FETCH_REQUEST = "FIXED_FETCH_REQUEST";
export const FIXED_FETCH_SUCCESS = "FIXED_FETCH_SUCCESS";
export const FIXED_FETCH_FAIL = "FIXED_FETCH_FAIL";

export const FIXED_DELETE_SUCCESS = "FIXED_DELETE_SUCCESS";
export const FIXED_UPDATE_SUCCESS = "FIXED_UPDATE_SUCCESS";

export const FIXED_UPLOAD_REQUEST = "FIXED_UPLOAD_REQUEST";
export const FIXED_UPLOAD_SUCCESS = "FIXED_UPLOAD_SUCCESS";
export const FIXED_UPLOAD_FAIL = "FIXED_UPLOAD_FAIL";
