export const FETCH_FIXED_PRICE_REQUEST = 'FETCH_FIXED_PRICE_REQUEST';
export const FETCH_FIXED_PRICE_SUCCESS = 'FETCH_FIXED_PRICE_SUCCESS';
export const FETCH_FIXED_PRICE_FAIL = 'FETCH_FIXED_PRICE_FAIL';

export const UPDATE_FIXED_PRICE_REQUEST = 'UPDATE_FIXED_PRICE_REQUEST';
export const UPDATE_FIXED_PRICE_SUCCESS = 'UPDATE_FIXED_PRICE_SUCCESS';
export const UPDATE_FIXED_PRICE_FAIL = 'UPDATE_FIXED_PRICE_FAIL';

export const SET_EDITING = 'SET_EDITING';
export const SET_NEW_AMOUNT = 'SET_NEW_AMOUNT';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
