// src/redux/process/processConstants.js
export const FETCH_CLIENTS_REQUEST = "FETCH_CLIENTS_REQUEST";
export const FETCH_CLIENTS_SUCCESS = "FETCH_CLIENTS_SUCCESS";
export const FETCH_CLIENTS_FAIL = "FETCH_CLIENTS_FAIL";

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_PROCESSES_REQUEST = "FETCH_PROCESSES_REQUEST";
export const FETCH_PROCESSES_SUCCESS = "FETCH_PROCESSES_SUCCESS";
export const FETCH_PROCESSES_FAIL = "FETCH_PROCESSES_FAIL";

export const SAVE_PROCESS_REQUEST = "SAVE_PROCESS_REQUEST";
export const SAVE_PROCESS_SUCCESS = "SAVE_PROCESS_SUCCESS";
export const SAVE_PROCESS_FAIL = "SAVE_PROCESS_FAIL";

export const DELETE_PROCESS_REQUEST = "DELETE_PROCESS_REQUEST";
export const DELETE_PROCESS_SUCCESS = "DELETE_PROCESS_SUCCESS";
export const DELETE_PROCESS_FAIL = "DELETE_PROCESS_FAIL";

export const SET_CLIENT = "SET_CLIENT";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_RATE = "SET_RATE";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_EDITING_PROCESS_ID = "SET_EDITING_PROCESS_ID";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
