export const FETCH_PROCESSES_REQUEST = "FETCH_PROCESSES_REQUEST";
export const FETCH_PROCESSES_SUCCESS = "FETCH_PROCESSES_SUCCESS";
export const FETCH_PROCESSES_FAIL = "FETCH_PROCESSES_FAIL";

export const FETCH_VERIFICATIONS_REQUEST = "FETCH_VERIFICATIONS_REQUEST";
export const FETCH_VERIFICATIONS_SUCCESS = "FETCH_VERIFICATIONS_SUCCESS";
export const FETCH_VERIFICATIONS_FAIL = "FETCH_VERIFICATIONS_FAIL";

export const SUBMIT_VERIFICATION_REQUEST = "SUBMIT_VERIFICATION_REQUEST";
export const SUBMIT_VERIFICATION_SUCCESS = "SUBMIT_VERIFICATION_SUCCESS";
export const SUBMIT_VERIFICATION_FAIL = "SUBMIT_VERIFICATION_FAIL";

export const DELETE_VERIFICATION_SUCCESS = "DELETE_VERIFICATION_SUCCESS";

export const SET_PROCESS = "SET_PROCESS";
export const SET_LOCATION = "SET_LOCATION";
export const SET_PRICE = "SET_PRICE";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_EDITING_ID = "SET_EDITING_ID";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
