// src/constants/verificationConstants.js

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_VERIFICATIONS_REQUEST = "FETCH_VERIFICATIONS_REQUEST";
export const FETCH_VERIFICATIONS_SUCCESS = "FETCH_VERIFICATIONS_SUCCESS";
export const FETCH_VERIFICATIONS_FAIL = "FETCH_VERIFICATIONS_FAIL";

export const FETCH_PAYOUTS_REQUEST = "FETCH_PAYOUTS_REQUEST";
export const FETCH_PAYOUTS_SUCCESS = "FETCH_PAYOUTS_SUCCESS";
export const FETCH_PAYOUTS_FAIL = "FETCH_PAYOUTS_FAIL";

export const ADD_PAYOUT_SUCCESS = "ADD_PAYOUT_SUCCESS";
export const UPDATE_PAYOUT_SUCCESS = "UPDATE_PAYOUT_SUCCESS";
export const DELETE_PAYOUT_SUCCESS = "DELETE_PAYOUT_SUCCESS";
